<?php
/**
 * List of recommended Google Fonts
 */

return array(
	'Abel' => array(
		'label' => 'Abel',
		'category' => 'sans-serif',
	),
	'Abril Fatface' => array(
		'label' => 'Abril Fatface',
		'category' => 'display',
	),
	'Amatic SC' => array( 'label' => 'Amatic SC', 'variants' => array( 'regular','700' ), 'category' => 'handwriting' ),
	'Amiri' => array( 'label' => 'Amiri', 'variants' => array( 'regular','italic','700','700italic' ), 'category' => 'serif' ),
	'Alegreya' => array(
		'label' => 'Alegreya',
		'variants' => array(
			'500',
			'500i',
			'700',
			'700i',
			'800',
			'800i',
			'900',
			'900i',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Alfa Slab One' => array(
		'label' => 'Alfa Slab One',
		'category' => 'display',
	),
	'Almendra Display' => array(
		'label' => 'Almendra Display',
		'category' => 'display',
	),
	'Alice' => array(
		'label' => 'Alice',
		'category' => 'serif',
	),
	'Belgrano' => array(
		'label' => 'Belgrano',
		'category' => 'serif',
	),
	'Cabin Sketch' => array(
		'label' => 'Cabin Sketch',
		'variants' => array(
			'700',
			'regular',
		),
		'category' => 'display',
	),
	'Cardo' => array(
		'label' => 'Cardo',
		'variants' => array(
			'700',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Caveat' => array( 'label' => 'Caveat', 'variants' => array( 'regular','700' ), 'category' => 'handwriting' ),
	'Caveat Brush' => array(
		'label' => 'Caveat Brush',
		'category' => 'handwriting',
	),
	'Comfortaa' => array( 'label' => 'Comfortaa', 'variants' => array( '300','regular','500','600','700' ), 'category' => 'display' ),
	'Cormorant' => array(
		'label' => 'Cormorant',
		'variants' => array(
			'300',
			'300i',
			'500',
			'500i',
			'600',
			'600i',
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Cormorant Garamond' => array( 'label' => 'Cormorant Garamond', 'variants' => array( '300','300italic','regular','italic','500','500italic','600','600italic','700','700italic' ), 'category' => 'serif' ),
	'Courgette' => array(
		'label' => 'Courgette',
		'category' => 'handwriting',
	),
	'Creepster' => array(
		'label' => 'Creepster',
		'category' => 'display',
	),
	'Crete Round' => array(
		'label' => 'Crete Round',
		'variants' => array(
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Crimson Text' => array(
		'label' => 'Crimson Text',
		'variants' => array(
			'600',
			'600i',
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Cuprum' => array(
		'label' => 'Cuprum',
		'variants' => array(
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Domine' => array(
		'label' => 'Domine',
		'variants' => array(
			'700',
			'regular',
		),
		'category' => 'serif',
	),
	'Dancing Script' => array(
		'label' => 'Dancing Script',
		'variants' => array(
			'700',
			'regular',
		),
		'category' => 'handwriting',
	),
	'DM Serif Display' => array( 'label' => 'DM Serif Display', 'variants' => array( 'regular','italic' ), 'category' => 'serif' ),
	'DM Serif Text' => array( 'label' => 'DM Serif Text', 'variants' => array( 'regular','italic' ), 'category' => 'serif' ),
	'Domine' => array( 'label' => 'Domine', 'variants' => array( 'regular','700' ), 'category' => 'serif' ),
	'EB Garamond' => array( 'label' => 'EB Garamond', 'variants' => array( 'regular','500','600','700','800','italic','500italic','600italic','700italic','800italic' ), 'category' => 'serif' ),
	'Exo' => array(
		'label' => 'Exo',
		'variants' => array(
			'100',
			'100i',
			'200',
			'200i',
			'300',
			'300i',
			'500',
			'500i',
			'600',
			'600i',
			'700',
			'700i',
			'800',
			'800i',
			'900',
			'900i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Fanwood Text' => array(
		'label' => 'Fanwood Text',
		'variants' => array(
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Fauna One' => array(
		'label' => 'Fauna One',
		'variants' => array(
			'regular',
		),
		'category' => 'serif',
	),
	'Fredericka the Great' => array(
		'label' => 'Fredericka the Great',
		'category' => 'display',
	),
	'Fugaz One' => array(
		'label' => 'Fugaz One',
		'category' => 'display',
	),
	'Gentium Basic' => array(
		'label' => 'Gentium Basic',
		'variants' => array(
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Gentium Book Basic' => array(
		'label' => 'Gentium Book Basic',
		'variants' => array(
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Great Vibes' => array(
		'label' => 'Great Vibes',
		'category' => 'handwriting',
	),
	'Handlee' => array(
		'label' => 'Handlee',
		'category' => 'handwriting',
	),
	'Hepta Slab' => array( 'label' => 'Hepta Slab', 'variants' => array( '100','200','300','regular','500','600','700','800','900' ), 'category' => 'serif' ),
	'Josefin Sans' => array(
		'label' => 'Josefin Sans',
		'variants' => array(
			'100',
			'100i',
			'300',
			'300i',
			'600',
			'600i',
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Josefin Slab' => array(
		'label' => 'Josefin Slab',
		'variants' => array(
			'100',
			'100i',
			'300',
			'300i',
			'600',
			'600i',
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Jost' => array( 'label' => 'Jost', 'variants' => array( '100','200','300','regular','500','600','700','800','900','100italic','200italic','300italic','italic','500italic','600italic','700italic','800italic','900italic' ), 'category' => 'sans-serif' ),
	'Judson' => array(
		'label' => 'Judson',
		'variants' => array(
			'700',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Julius Sans One' => array(
		'label' => 'Julius Sans One',
		'category' => 'sans-serif',
	),
	'Kalam' => array( 'label' => 'Kalam', 'variants' => array( '300','regular','700' ), 'category' => 'handwriting' ),
	'Kaushan Script' => array(
		'label' => 'Kaushan Script',
		'category' => 'handwriting',
	),
	'Lato' => array( 'label' => 'Lato', 'variants' => array( '100','100italic','300','300italic','regular','italic','700','700italic','900','900italic' ), 'category' => 'sans-serif' ),
	'Libre Baskerville' => array(
		'label' => 'Libre Baskerville',
		'variants' => array(
			'700',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Limelight' => array(
		'label' => 'Limelight',
		'category' => 'display',
	),
	'Lobster' => array(
		'label' => 'Lobster',
		'category' => 'display',
	),
	'Lora' => array(
		'label' => 'Lora',
		'variants' => array(
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Megrim' => array(
		'label' => 'Megrim',
		'category' => 'display',
	),
	'Monda' => array(
		'label' => 'Monda',
		'variants' => array(
			'700',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Monoton' => array(
		'label' => 'Monoton',
		'category' => 'display',
	),
	'Montserrat' => array(
		'label' => 'Montserrat',
		'variants' => array(
			'100',
			'100i',
			'200',
			'200i',
			'300',
			'300i',
			'500',
			'500i',
			'600',
			'600i',
			'700',
			'700i',
			'800',
			'800i',
			'900',
			'900i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Muli' => array(
		'label' => 'Muli',
		'variants' => array(
			'200',
			'200i',
			'300',
			'300i',
			'600',
			'600i',
			'700',
			'700i',
			'800',
			'800i',
			'900',
			'900i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Neuton' => array(
		'label' => 'Neuton',
		'variants' => array(
			'200',
			'300',
			'700',
			'800',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Nixie One' => array(
		'label' => 'Nixie One',
		'category' => 'display',
	),
	'Old Standard TT' => array(
		'label' => 'Old Standard TT',
		'variants' => array(
			'700',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Oleo Script' => array(
		'label' => 'Oleo Script',
		'variants' => array(
			'700',
			'regular',
		),
		'category' => 'display',
	),
	'Open Sans' => array(
		'label' => 'Open Sans',
		'variants' => array(
			'300',
			'300i',
			'600',
			'600i',
			'700',
			'700i',
			'800',
			'800i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Open Sans Condensed' => array(
		'label' => 'Open Sans Condensed',
		'variants' => array(
			'300',
			'300i',
			'700',
		),
		'category' => 'sans-serif',
	),
	'Oswald' => array(
		'label' => 'Oswald',
		'variants' => array(
			'200',
			'300',
			'500',
			'600',
			'700',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Ovo' => array(
		'label' => 'Ovo',
		'variants' => array(
			'regular',
		),
		'category' => 'serif',
	),
	'Parisienne' => array( 'label' => 'Parisienne', 'category' => 'handwriting' ),
	'Prata' => array( 
	    'label' => 'Prata', 
	    'variants' => array( 'regular' ), 
	    'category' => 'serif'
	),
	'Permanent Marker' => array(
		'label' => 'Permanent Marker',
		'variants' => array(
			'regular',
		),
		'category' => 'handwriting',
	),
	'Philosopher' => array(
		'label' => 'Philosopher',
		'variants' => array(
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Playball' => array(
		'label' => 'Playball',
		'category' => 'display',
	),
	'Playfair Display' => array(
		'label' => 'Playfair Display',
		'variants' => array(
			'700',
			'700i',
			'900',
			'900i',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Playfair Display SC' => array(
		'label' => 'Playfair Display SC',
		'variants' => array(
			'700',
			'700i',
			'900',
			'900i',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Poppins' => array(
		'label' => 'Poppins',
		'variants' => array(
			'100',
			'100i',
			'200',
			'200i',
			'300',
			'300i',
			'regular',
			'italic',
			'500',
			'500i',
			'600',
			'600i',
			'700',
			'700i',
			'800',
			'800i',
			'900',
			'900i',

		),
		'category' => 'sans-serif',
	),
	'Public Sans' => array( 'label' => 'Public Sans', 'variants' => array( '100','200','300','regular','500','600','700','800','900','100italic','200italic','300italic','italic','500italic','600italic','700italic','800italic','900italic' ), 'category' => 'sans-serif' ),
	'Quando' => array(
		'label' => 'Quando',
		'category' => 'serif',
	),
	'Quattrocento' => array(
		'label' => 'Quattrocento',
		'variants' => array(
			'700',
			'regular',
		),
		'category' => 'serif',
	),
	'Quattrocento Sans' => array(
		'label' => 'Quattrocento Sans',
		'variants' => array(
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Questrial' => array(
		'label' => 'Questrial',
		'category' => 'sans-serif',
	),
	'Raleway' => array(
		'label' => 'Raleway',
		'variants' => array(
			'100',
			'100i',
			'200',
			'200i',
			'300',
			'300i',
			'500',
			'500i',
			'600',
			'600i',
			'700',
			'700i',
			'800',
			'800i',
			'900',
			'900i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Roboto' => array(
		'label' => 'Roboto',
		'variants' => array(
			'100',
			'100i',
			'300',
			'300i',
			'500',
			'500i',
			'700',
			'700i',
			'900',
			'900i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Roboto Condensed' => array(
		'label' => 'Roboto Condensed',
		'variants' => array(
			'300',
			'300i',
			'700',
			'700i',
			'italic',
			'regular',
		),
		'category' => 'sans-serif',
	),
	'Roboto Slab' => array(
		'label' => 'Roboto Slab',
		'variants' => array(
			'100',
			'300',
			'700',
			'regular',
		),
		'category' => 'serif',
	),
	'Satisfy' => array(
		'label' => 'Satisfy',
		'category' => 'handwriting',
	),
	'Sacramento' => array(
		'label' => 'Sacramento',
		'category' => 'handwriting',
	),
	'Sail' => array(
		'label' => 'Sail',
		'category' => 'display',
	),
	'Sorts Mill Goudy' => array(
		'label' => 'Sorts Mill Goudy',
		'variants' => array(
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Spartan' => array( 'label' => 'Spartan', 'variants' => array( '100','200','300','regular','500','600','700','800','900' ), 'category' => 'sans-serif' ),
	'Stint Ultra Expanded' => array(
		'label' => 'Stint Ultra Expanded',
		'category' => 'display',
	),
	'Ultra' => array(
		'label' => 'Ultra',
		'category' => 'serif',
	),
	'Unica One' => array(
		'label' => 'Unica One',
		'category' => 'display',
	),
	'Vast Shadow' => array(
		'label' => 'Vast Shadow',
		'category' => 'display',
	),
	'Vollkorn' => array(
		'label' => 'Vollkorn',
		'variants' => array(
			'600',
			'600i',
			'700',
			'700i',
			'900',
			'900i',
			'italic',
			'regular',
		),
		'category' => 'serif',
	),
	'Vollkorn SC' => array(
		'label' => 'Vollkorn SC',
		'variants' => array(
			'600',
			'700',
			'900',
			'regular',
		),
		'category' => 'serif'
	),
	'Work Sans' => array( 'label' => 'Work Sans', 'variants' => array( '100','200','300','regular','500','600','700','800','900','100italic','200italic','300italic','italic','500italic','600italic','700italic','800italic','900italic' ), 'category' => 'sans-serif' ),
);
